### ISSUE TITLE
Default Tests Not Found

### ISSUE THREAD

**Issue by AdamBrodzinski** [reasonml-old/reason-scripts#74]
Hello,

I'm using the latest `1.0.0-beta4` and when I do a `yarn test` the test that's included does not run. I'm pretty sure at some point in the past it did run however. I'm more than happy to setup a repro and give more info but I wasn't sure if this was a known problem. 

However, i've figured out how to narrow it down and make those tests pass.

**Option 1**
First I have to remove the `.bs.js` to get it to see the js file then change the `_test` to `.test`... eg change `app_test.bs.js` to `app.test.js` then jest picks up the file and shows me the pass/fail as expected. This isn't useable of course but at least shines some light onto a file pattern matching issue.

**Option 2**
Put the tests in a `__tests__` directory and turn on `subdirs` in the bsconfig.

OSX 10.12.4
bs-platform - 4.0.3
1.0.0-beta-4

Thanks for all you're hard work! 🍺 🎉

**Comment by rrdelaney** [comment]
Hi there 😁 tests are broken right now for Reason-scripts, and we don’t have a good plan to fix it. 

The problem is that compiling to ES6 modules entirely breaks Jest, because BuckleScript also compiles node_modules to ES6 modules. Jest doesn’t process these, so everything ends up broken. It’s a choice of either ES6 modules at the moment, or tests 😕

**Comment by RawToast** [comment]
I've had issues with reason-scripts for tests and coverage for some time and ended up calling jest instead for simple testing.

`"test": "jest --env=jsdom --testMatch='**/test/*test.{js, re}' --watch"`

Also stuck on `0.8.0` since I can't get code coverage to work with later versions 😿 

@rrdelaney Bit of an issue high-jack, I noticed reason-scripts is now in `reasonml-old`, I presume users should be looking to migrate away from these scripts? Are there plans for a successor project? Or should I stop being lazy and learn how to configure my projects? 😆

**Comment by rrdelaney** [comment]
@RawToast Best way to run a Reason project in my experience is to use `bsb -init && yarn add --dev parcel`. There's no hacks like `bs-loader` had and is a much more stable setup.
